[workspace]
authors = ["Vernonicuhhh <Vernonicuhhh@protonmail.com>"]
channels = ["https://prefix.dev/robostack-humble", "https://prefix.dev/conda-forge"]
name = "ros2_ws"
platforms = [
  { name = "linux-64-cuda", platform = "linux-64", cuda = "13" },
  "linux-aarch64",
]
version = "0.1.0"

# The default environment remains the NVIDIA desktop environment used on Linux.
[feature.linux-cuda]
platforms = ["linux-64-cuda"]

[feature.linux-cuda.tasks]
build = "colcon build --parallel-workers $(nproc) --symlink-install --event-handlers console_direct+ --base-paths src --cmake-args ' -DCMAKE_BUILD_TYPE=Release' ' -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs' ' -DCMAKE_CXX_FLAGS=\"-Wl,--allow-shlib-undefined\"'"

[feature.linux-cuda.dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = "*"
flake8-docstrings = "*"
pytest-cov = "*"
ros-humble-turtlesim = ">=1.4.3,<2"

[feature.linux-cuda.pypi-dependencies]
argcomplete = "*"
numpy = "*"
empy = "*"
lark = "*"

# CPU-only environment for Apple-Silicon Docker Desktop containers.
[feature.mac-cpu]
platforms = ["linux-aarch64"]

[feature.mac-cpu.tasks]
build = "colcon build --parallel-workers $(nproc) --symlink-install --event-handlers console_direct+ --base-paths src --cmake-args ' -DCMAKE_BUILD_TYPE=Release'"

[feature.mac-cpu.dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = "*"
flake8-docstrings = "*"
pytest-cov = "*"
ros-humble-turtlesim = ">=1.4.3,<2"

[feature.mac-cpu.pypi-dependencies]
argcomplete = "*"
numpy = "*"
empy = "*"
lark = "*"

[environments]
default = { features = ["linux-cuda"]}
mac-cpu = { features = ["mac-cpu"]}

[dependencies]
ros-humble-xacro = "*"
ros-humble-joint-state-publisher-gui = ">=2.4.0,<3"
ros-humble-robot-state-publisher = ">=3.0.3,<4"
ros-humble-ament-cmake-auto = ">=1.3.14,<2"
compilers = ">=1.11.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = "<4"
ninja = ">=1.13.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-ros-gz = ">=0.244.24,<0.245"
ros-humble-controller-manager = ">=2.54.0,<3"
ros-humble-ros2-controllers = ">=2.53.1,<3"
ros-humble-gz-ros2-control = ">=0.7.19,<0.8"
ruff = ">=0.16.2,<0.17"

[activation]
scripts = ["install/setup.sh"]

[tasks]
fmt = "ruff check src/ --fix"
