ARG UBUNTU_MAJOR=22
ARG UBUNTU_MINOR=04
ARG CUDA_MAJOR=13
ARG CUDA_MINOR=2
ARG CUDA_PATCH=1
ARG ZED_SDK_MAJOR=5
ARG ZED_SDK_MINOR=4
ARG ZED_SDK_PATCH=0


FROM nvcr.io/nvidia/cuda:${CUDA_MAJOR}.${CUDA_MINOR}.${CUDA_PATCH}-devel-ubuntu${UBUNTU_MAJOR}.${UBUNTU_MINOR}

ARG UBUNTU_MAJOR=22
ARG UBUNTU_MINOR=04
ARG CUDA_MAJOR=13
ARG CUDA_MINOR=2
ARG CUDA_PATCH=1
ARG ZED_SDK_MAJOR=5
ARG ZED_SDK_MINOR=4
ARG ZED_SDK_PATCH=0
ARG PIXI_VERSION=0.76.1
# Optional: Override ZED SDK URL
ARG CUSTOM_ZED_SDK_URL=""

ARG CONDA_OVERRIDE_CUDA=13.2
ENV CONDA_OVERRIDE_CUDA=${CONDA_OVERRIDE_CUDA}

# create a non-root user
ARG USERNAME=ros_user
ARG USER_UID=1000
ARG USER_GID=1000

ARG DEBIAN_FRONTEND=noninteractive

ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,video,utility

RUN apt-get update || true && apt-get install -y --no-install-recommends \
  apt-utils \
  curl \
  dialog && \
  rm -rf /var/lib/apt/lists/*

ENV ZED_SDK_URL=${CUSTOM_ZED_SDK_URL:-"https://download.stereolabs.com/zedsdk/${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}.${ZED_SDK_PATCH}/cu${CUDA_MAJOR}/ubuntu${UBUNTU_MAJOR}"}

RUN echo "SDK link: $ZED_SDK_URL"
RUN if [ "$(curl -L -I "${ZED_SDK_URL}" -o /dev/null -s -w '%{http_code}\n' | head -n 1)" = "200" ]; then \
        echo "The URL points to something."; \
    else \
        echo "The URL does not point to a .run file or the file does not exist."; \
        exit 1; \
    fi

ENV TZ=Europe/Paris

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
  apt-get update && \
  apt-get install --yes \
  build-essential \
  cmake \
  git \
  jq \
  less \
  libopencv-dev \
  libpq-dev \
  lsb-release \
  python3 \
  python3-dev \
  python3-pip \
  python3-wheel \
  sudo \
  udev \
  usbutils \
  wget \
  zstd && \
  rm -rf /var/lib/apt/lists/*

RUN echo "CUDA Version $CUDA_VERSION" > /usr/local/cuda/version.txt

RUN apt-get update -y || true && \
  apt-get install --no-install-recommends \
  bash-completion \
  build-essential \
  cmake \
  dialog \
  less \
  libgomp1 \
  libpng-dev \
  lsb-release \
  python3 \
  python3-pip \
  sudo \
  tmux \
  udev \
  wget \
  zstd \
  -y && \
  python3 -m pip install --upgrade pip; python3 -m pip install \
  numpy \
  opencv-python-headless && \
  wget -q -O ZED_SDK_Linux_Ubuntu.run ${ZED_SDK_URL}

RUN groupadd --gid ${USER_GID} ${USERNAME} && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m -s /bin/bash ${USERNAME} && \
    mkdir -p /home/${USERNAME}/ros2_ws/src && \
    chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/ros2_ws && \
    usermod -aG sudo ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}


#this step will fail if the wget was invalid (e.g. the download link returned a 404 then the head should show html)
RUN chmod +x ZED_SDK_Linux_Ubuntu.run && \
  bash ./ZED_SDK_Linux_Ubuntu.run -- silent skip_tools skip_cuda && \
  ln -sf /lib/x86_64-linux-gnu/libusb-1.0.so.0 /usr/lib/x86_64-linux-gnu/libusb-1.0.so && \
  rm ZED_SDK_Linux_Ubuntu.run && \
  rm -rf /var/lib/apt/lists/*

ENV PIXI_HOME=/opt/pixi
ENV PATH=${PIXI_HOME}/bin:${PATH}

RUN curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=v${PIXI_VERSION} PIXI_HOME=${PIXI_HOME} bash

#ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
USER ${USERNAME}
CMD ["pixi", "shell"]
